# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rangetastic}
  s.version = "0.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Herring"]
  s.date = %q{2009-11-20}
  s.description = %q{Filter dates for ActiveRecord using very simple _between syntax}
  s.email = %q{chris.herring.iphone@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "MIT-License",
     "Manifest",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/rangetastic.rb",
     "rangetastic.gemspec",
     "spec/rangetastic_spec.rb",
     "spec/spec_helper.rb",
  ]
  s.homepage = %q{http://github.com/cherring/rangetastic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple filtering by date ranges for ActiveRecord}
  s.test_files = [
     "spec/rangetastic_spec.rb",
     "spec/spec_helper.rb",
  ]
  
  s.add_dependency "rails", ">=3.1.2"
  s.add_development_dependency "jeweler"
  s.add_development_dependency "rspec"
  s.add_development_dependency "ruby-debug"
  s.add_development_dependency "combustion", '~> 0.3.1'
  s.add_development_dependency "sqlite3"
end

